
semaphore: semaphore.cpp
	g++ semaphore.cpp -std=c++11 -lpthread -o semaphore
	time ./semaphore
pthread_spinlock: pthread_spinlock.cpp
	g++ pthread_spinlock.cpp -std=c++11 -lpthread -o pthread_spinlock
	time ./pthread_spinlock
homemade_spinlock: homemade_spinlock.cpp
	g++ homemade_spinlock.cpp -std=c++11 -lpthread -fpermissive -o homemade_spinlock
	time ./homemade_spinlock
